modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="immortalstorage.refinedstorage.mixins.json"

[[mixins]]
config="immortalstorage.core.mixins.json"

[[mixins]]
config="immortalstorage.buildinggadgets.mixins.json"

[[mixins]]
config="immortalstorage.arsnouveau.mixins.json"

[[mixins]]
config="immortalstorage.appliedbotanics.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="${emi_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="${ae2_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="optional"
versionRange="${refinedstorage_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedtypes"
type="optional"
versionRange="${refinedtypes_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage_mekanism_integration"
type="optional"
versionRange="${rs_mekanism_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botania"
type="optional"
versionRange="${botania_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
type="optional"
versionRange="${mekanism_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="industrialforegoingsouls"
type="optional"
versionRange="${industrialforegoingsouls_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beyonddimensions"
type="optional"
versionRange="${beyonddimensions_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ars_nouveau"
type="optional"
versionRange="${ars_nouveau_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
type="${patchouli_dependency_type}"
versionRange="${patchouli_version_range}"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9.5.1,)"
ordering="AFTER"
side="BOTH"
