org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
neo_version_range=[21.1.235]
loader_version_range=[4,)
compatibility_id=neoforge-mc1.21.1-nf21.1.235
core_source_dir=../cultivation-core/src/main/java
compatibility_source_dir=../version-compat/neoforge/mc-1.21.1-nf-21.1.235/src/main/java
compatibility_descriptor_file=../version-compat/neoforge/mc-1.21.1-nf-21.1.235/compatibility.json

## Mod Properties

mod_id=cultivation
mod_name=Cultivation
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=com.cultivation.cultivation
mod_authors=YourNameHere
mod_description=Storage Cultivation Mod: items, custom dimension, storage per player, tribulation system, source veins, AE2/RS/FTB hooks.
